project:
  type: website
  output-dir: _site

website:
  page-navigation: true
  title: "CUS - Spring 2025"
  description: "Homepage for Computational Urban Science - Network Science Institute, Spring 2025."
  site-url: "https://socialurban.net/CUS"
  repo-url: "https://github.com/SUNLab-NetSI/CUS"
  repo-actions: [edit, issue]
  
  open-graph: true
  
  twitter-card: 
    creator: "@estebanmoro"
    image: "images/twitter-card.png"
    
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, SUNLab, Northeastern University"
    background: "#D9E3E4"
  
  sidebar: 
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/SUNLab-NetSI/CUS
        text: "Course Github Repo"
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course Information"
        contents: 
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
#          - href: course-links.qmd
#            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Access to the server
          - href: computing-working.qmd
            text: Working with the server
      - section: "Project"
        contents:
          - href: project-description.qmd
            text: Description
          - href: project-tips-resources.qmd
            text: Tips + resources
      - section: "Weekly materials"
        contents:
          - href: weeks/week-1.qmd
            text: Week 1 (Jan 7)
      - section: "Supplemental notes"
        contents:
          - href: supplemental/other-visualization-tools.qmd
            text: Other visualization tools

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    
freeze: auto

editor: visual

