project:
  type: website
  output-dir: _site

website:
  page-navigation: true
  title: "CUS - Spring 2025"
  description: "Homepage for Computational Urban Science - Network Science Institute, Spring 2025."
  site-url: "https://socialurban.net/CUS"
  repo-url: "https://github.com/SUNLab-NetSI/CUS"
  repo-actions: [edit, issue]
  
  open-graph: true
  
  twitter-card: 
    creator: "@estebanmoro"
    image: "images/twitter-card.png"
    
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Esteban Moro"
    background: "#D9E3E4"
  
  sidebar: 
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course Information"
        contents: 
          - href: index.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-team.qmd
            text: Teaching team
          - href: about.qmd
            text: About
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Access

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    
freeze: auto

editor: visual

