---
title: "NETS 7983 Computational Urban Science"
tbl-colwidths: [5,15,30,5,5,5,5,5]
---

Welcome to the homepage of *Computational Urban Science*, NETS 7983 course in the *Network Science* PhD Program in Northeastern University

This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
|           Week           | Date        | Topic                                                |                  Prepare                  |                 Slides                  |                     Lab                     |         HW          |                  Project                   |     |     |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| [1](/weeks/week-1.html)  | Tue Jan 7   | Introduction to the course                           | [📖](/weeks/week-1.html "Week 1 Summary") |                                         |                                             |                     |                                            |     |     |
|                          |             | Lecture 1-1 - Welcome to CUS 2025                    |                                           | [🖥️](/slides/lec-1-1.html "Lab slides") |                                             |                     |                                            |     |     |
|                          |             | Lecture 1-2 - Intro to Computational Urban Science   |                                           | [🖥️](/slides/lec-1-2.html "Lab slides") |                                             |                     |                                            |     |     |
|                          |             | Lab 1-1 - Crash course on GIS using R                |                                           |                                         | [💻](/labs/lab-1-1.html "Lab instructions") |                     |                                            |     |     |
|                          |             | Lab 1-2 - Collect your own mobility data             |                                           |                                         | [💻](/labs/lab-1-2.html "Lab instructions") |                     |                                            |     |     |
| [2](/weeks/week-2.html)  | Tue Jan 14  | Urban Data - Maps + Census                           | [📖](/weeks/week-2.html "Week 2 Summary")                                          |                                         |                                             |                     |                                            |     |     |
| [3](/weeks/week-3.html)  | Tue Jan 21  | Urban Data - Activity: Mobile Phone                  |                                           |                                         |                                             |                     |                                            |     |     |
| [4](/weeks/week-4.html)  | Tue Jan 28  | Urban Data - Activity: Social Media + Ethics         |                                           |                                         |                                             |                     |                                            |     |     |
| [5](/weeks/week-5.html)  | Tue Feb 4   | Statistical Analysis of Urban Data                   |                                           |                                         |                                             |                     |                                            |     |     |
| [6](/weeks/week-6.html)  | Tue Feb 11  | Statistical Inference with Urban Data                |                                           |                                         |                                             |                     |                                            |     |     |
|                          | Wed Feb 12  | Released: HW 1                                       |                                           |                                         |                                             | [✍️](/hw/hw-1.html) |                                            |     |     |
| [7](/weeks/week-7.html)  | Tue Feb 18  | Causal Inference for Urban Data                      |                                           |                                         |                                             |                     |                                            |     |     |
| [8](/weeks/week-8.html)  | Tue Feb 25  | Models - Urban Mobility models                       |                                           |                                         |                                             |                     |                                            |     |     |
| [9](/weeks/week-5.html)  | Tue Mar 4   | NU Spring Break                                      |                                           |                                         |                                             |                     |                                            |     |     |
| [10](/weeks/week-6.html) | Tue Mar 11  | Models - Urban Social Models and Network Models      |                                           |                                         |                                             |                     |                                            |     |     |
|                          | Wed Mar 12  | Released: HW 2                                       |                                           |                                         |                                             | [✍️](/hw/hw-1.html) |                                            |     |     |
| [11](/weeks/week-7.html) | Tue Mar 18  | Models - Agent-based models + Hypothesis testing     |                                           |                                         |                                             |                     |                                            |     |     |
| [12](/weeks/week-1.html) | Tue Mar 25  | Applications - Recommendation / Geomarketing         |                                           |                                         |                                             |                     |                                            |     |     |
| [13](/weeks/week-1.html) | Tue Apr 1   | Applications - Sustainability / Inequality           |                                           |                                         |                                             |                     |                                            |     |     |
| [14](/weeks/week-1.html) | Tue Apr 8   | Applications - Epidemic spreading.                   |                                           |                                         |                                             |                     |                                            |     |     |
|                          | Wed Apr 9   | Project topic ideas                                  |                                           |                                         |                                             |                     | [📂](project-description.html#topic-ideas) |     |     |
| [15](/weeks/week-1.html) | Tue Apr 15  | Applications: Climate change / Resilience            |                                           |                                         |                                             |                     |                                            |     |     |
| [16](/weeks/week-1.html) | Tue Apr 22  | Applications: Analysis of Policy Inteventions        |                                           |                                         |                                             |                     |                                            |     |     |
|                          | Fri Apr 25  | Project presentations                                |                                           |                                         |                                             |                     | [📂](project-description.html#topic-ideas) |     |     |
:::
