---
title: "Week 1"
subtitle: "Welcome to CUS 2025"
editor: visual
bibliography: ../references.bib
csl: ../nature-communications.csl
---

Welcome to the course! This week we will introduce the course, ourselves, and how to access the computing resources. We will also present a brief introduction to *Computational Urban Science* and a Crash Course on GIS with `R`.

## Prepare

📖 Read the [syllabus](/course-syllabus.html) of the course.

📖 Read the Computing resources

-   [Access to the computing server](/computing-access.html)
-   [Working with the server](/computing-working.html)

📖 Read some general bibliography about Computational Social Science and Urban Science

-   [Computational Social Science, Lazer et al 2009](/pdfs/ComputationalSocialScience.pdf) [@lazer2009computational]

-   [Computational Social Science: obstacles and opportunities](/pdfs/ComputationalSocialScience2.pdf) @lazer_computational_2020

-   [Chapter 2 of *Bit by Bit* book by Salganik](/pdfs/BitbyBit.pdf) @salganik2019bit

-   [Cities as Complex Systems - Batty](/pdfs/Cities_Complex_Systems_Batty_2008.pdf) @batty2009cities

-   [The city is not a static tree - Moro](/pdfs/city-not-a-static-tree.pdf) @moro2022city

## Participate

🖥️ [Lecture 1-1 : Welcome to CUS 2025!](/slides/lec-1-1.html)

🖥️ [Lecture 1-2 : Introduction to Computational Urban Science](/slides/lec-1-2.html)

🖥️ [Lab 1-1 : Crash course on GIS with R](/labs/lab-1-1.html)

🖥️ [Lab 1-2 : Collect and analyze you own mobility data](/labs/lab-1-2.html)


<br><br>

::: {style="font-size: 0.875em;"}
Back to [course schedule](/) ⏎
:::
