name: Build and Deploy Quarto Website

on:
  push:
    branches:
      - main

permissions: 
  id-token: write
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RENV_PATHS_CACHE: ~/.cache/R/renv

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache renv Packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Preserve Pre-Rendered Labs
        run: |
          mkdir -p .temp_labs
          if [ -d "_site/labs" ]; then
            cp _site/labs/*.html .temp_labs/ || true
          fi

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            libcurl4-openssl-dev \
            gdal-bin \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libudunits2-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libxml2-dev \
            libgit2-dev 
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.5.57'

      - name: Install TinyTeX
        run: |
          quarto install tinytex

      - name: Install R and renv
        run: |
          sudo apt-get install -y r-base
          R -e 'install.packages("renv", repos="https://cloud.r-project.org")'

      - name: Restore R Packages
        run: |
          R -e 'renv::restore()'

      - name: Render Quarto Project (Exclude Labs)
        run: |
          while IFS= read -r file; do
            echo "Rendering $file"
            quarto render "$file"
          done < <(find . -name '*.qmd' -not -path './labs/*')
        shell: bash

      - name: Restore Pre-Rendered Labs
        run: |
          mkdir -p _site/labs
          cp .temp_labs/*.html _site/labs/ || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
