name: Build and Deploy Quarto Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - 
        sudo apt-get install -y nodejs
    
    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Install TinyTeX
      run: |
        quarto install tinytex

    - name: Render Quarto Project
      run: |
        quarto render

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
