name: Build and Deploy Quarto Website

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - 
        sudo apt-get install -y nodejs
    
    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Install TinyTeX
      run: |
        quarto install tinytex

    - name: Install R and renv
      run: |
        sudo apt-get install -y r-base
        R -e 'install.packages("renv", repos="https://cloud.r-project.org")'

    - name: Restore R Packages
      run: |
        R -e 'renv::restore()'

    - name: Render Quarto Project
      run: |
        quarto render
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./_site 

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
          preview: false